default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sales_crm_development

test:
  <<: *default
  database: sales_crm_test

production:
  primary: &primary_production
    <<: *default
    database: sales_crm_production
    username: sales_crm
    password: <%= ENV["SALES_CRM_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: sales_crm_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: sales_crm_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: sales_crm_production_cable
    migrations_paths: db/cable_migrate
